# Generated by Django 5.0.6 on 2024-06-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='david', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
